on: [push, pull_request]
name: ShellCheck scripts
jobs:
  shellCheck:
    name: ShellCheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run shellcheck.
      run: shellcheck aliases apps build-caesium build-kernel common devtools files functions gitshit paste setup.sh server system ssh-copy-id-github.sh telegram setup/common.sh setup/diff-so-fancy.sh setup/gdrive.sh setup/hugo.sh setup/hub.sh setup/llvm.sh setup/nano.sh setup/ripgrep.sh setup/sharkdp.sh setup/shellcheck.sh setup/xclip.sh bash_completions.bash
