on: [push, pull_request]
name: ShellCheck scripts
jobs:
  shellCheck:
    name: ShellCheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/cache@v1
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go
        restore-keys: |
          ${{ runner.os }}-go-
    - name: Install shfmt
      run: GO111MODULE=on go get mvdan.cc/sh/v3/cmd/shfmt
    - name: Run shellcheck.
      run: PATH=$HOME/go/bin:$PATH make
